# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170418_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Player'),
        ),
    ]
