# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Another Spyfell Session', max_length=300)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
    ]
