# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170416_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('active_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Session')),
            ],
        ),
    ]
