# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170416_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Session'),
        ),
    ]
