# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_session_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Session'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Location'),
        ),
        migrations.AlterField(
            model_name='session',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Location'),
        ),
    ]
